### ISSUE TITLE
Doenst work

### ISSUE THREAD

**Issue by Zionnod** [Still34/AffinityPatcher#1]
Closes instantly when i try to open it.

**Comment by Still34** [comment]
You're gonna have to be more descriptive than that. What closes instantly? What does the patcher say?

**Comment by Zionnod** [comment]
> You're gonna have to be more descriptive than that. What closes instantly? What does the patcher say?

Ok so basically, when I try to Open the patcher, he opens for like 0.5 second and then closes instantly, I don't have even time to ready the content inside the patcher.

**Comment by Still34** [comment]
It's a CLI tool. It does not have a GUI. You are expected to interact with it via a terminal.

**Comment by Still34** [comment]
Shift right click in the Explorer window, Open in PowerShell, `./<program_name> --help` to execute and view the instructions.
